server:
  port: 8088

spring:
  profiles:
    active: dev

logging:
  level:
    root: info

sureness:
  enable: true
  supportType: servlet
  authType:
    - jwt
  token: ?::4s9ssf2sf4sed45pf):RnLN7XNn4wARoQXizIv6MHUsIV+EFfiMw/x7R0ntu4aWr/CWuApcFajCyaFv0bwq2Eik0jdrKUtsA6bx3sDJeFV643R+YYzGMRIqcBIp6AKA98GM2RIqcBIp6-?::4390fsf4sdl6opf)4ZI:tdQMtcQQ14pkOAQdQ546
  scanPackages:
    - com.usthe.sureness.bootstrap